cache golang lint ci

diff --git a/.github/workflows/pre-commit-hooks.yaml b/.github/workflows/pre-commit-hooks.yaml
--- a/.github/workflows/pre-commit-hooks.yaml
+++ b/.github/workflows/pre-commit-hooks.yaml
@@ -12,16 +12,49 @@ jobs:
   pre-commit:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
-      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
+      - name: Checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Setup Python
+        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
+
+      - name: Setup Go
+        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
         with:
           go-version: "stable"
-      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/2b224c2cf4c9f261c22a16af7f8ca6408467f338/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
-      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
+
+      - name: Cache golangci-lint
+        uses: actions/cache@v4
+        with:
+          path: ~/.cache/golangci-lint
+          key: golangci-lint-2.0.2
+
+      - name: Ensure golangci-lint is installed
+        run: |
+          set -e
+          export GOLANGCI_LINT_VERSION=v2.0.2
+          export GOLANGCI_LINT_BIN="$HOME/.cache/golangci-lint/golangci-lint"
+          if [ -x "$GOLANGCI_LINT_BIN" ]; then
+            echo "golangci-lint found in cache."
+          else
+            echo "golangci-lint not found in cache, installing with curl..."
+            mkdir -p "$HOME/.cache/golangci-lint"
+            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$HOME/.cache/golangci-lint" $GOLANGCI_LINT_VERSION
+          fi
+          echo "$HOME/.cache/golangci-lint" >> $GITHUB_PATH
+
+      - name: Cache pre-commit
+        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
         with:
           path: ~/.cache/pre-commit
           key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
-      - run: python -m pip install pre-commit
-      - run: pre-commit run --all-files --show-diff-on-failure --color=always
+
+      - name: Install pre-commit
+        run: python -m pip install pre-commit
+
+      - name: Run pre-commit
+        run: pre-commit run --all-files --show-diff-on-failure --color=always
         shell: bash
+
+      - name: Run golangci-lint
+        run: golangci-lint run --fix
